apiVersion: apps/v1
kind: Deployment
metadata:
  name: streaming-pipeline
  namespace: seismic-insights
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streaming-pipeline
  template:
    metadata:
      labels:
        app: streaming-pipeline
    spec:
      containers:
      - name: streaming-pipeline
        image: seismic-insights/streaming-pipeline:latest
        imagePullPolicy: Never  # Locally built image
        ports:
        - containerPort: 8081
        envFrom:
        - configMapRef:
            name: seismic-config
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              name: seismic-config
              key: KAFKA_BOOTSTRAP_SERVERS
        - name: KAFKA_TOPICS
          valueFrom:
            configMapKeyRef:
              name: seismic-config
              key: KAFKA_TOPICS
        - name: KAFKA_GROUP_ID
          valueFrom:
            configMapKeyRef:
              name: seismic-config
              key: KAFKA_GROUP_ID
        - name: KAFKA_SOURCE_NAME
          valueFrom:
            configMapKeyRef:
              name: seismic-config
              key: KAFKA_SOURCE_NAME
        - name: INFLUXDB_URL
          valueFrom:
            configMapKeyRef:
              name: seismic-config
              key: INFLUXDB_URL
        - name: INFLUXDB_TOKEN
          valueFrom:
            secretKeyRef:
              name: seismic-secrets
              key: INFLUXDB_TOKEN
        - name: INFLUXDB_ORG
          valueFrom:
            configMapKeyRef:
              name: seismic-config
              key: INFLUXDB_ORG
        - name: INFLUXDB_BUCKET
          valueFrom:
            configMapKeyRef:
              name: seismic-config
              key: INFLUXDB_BUCKET
        - name: MIN_MAGNITUDE
          valueFrom:
            configMapKeyRef:
              name: seismic-config
              key: MIN_MAGNITUDE
        - name: JOB_NAME
          valueFrom:
            configMapKeyRef:
              name: seismic-config
              key: JOB_NAME
        resources:
          requests:
            cpu: "4"
          limits:
            cpu: "4"
      restartPolicy: Always
