apiVersion: v1
kind: Service
metadata:
  name: streaming-pipeline
  namespace: seismic-insights
spec:
  selector:
    app: streaming-pipeline
  ports:
  - name: flink-ui
    port: 8081
    targetPort: 8081
    nodePort: 30081
  type: NodePort
