apiVersion: v1
kind: Service
metadata:
  name: influxdb
  namespace: seismic-insights
spec:
  selector:
    app: influxdb
  ports:
  - name: influxdb
    port: 8086
    targetPort: 8086
    nodePort: 30086
  type: NodePort
