global:

route:
  group_by: ['alertname', 'region']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'
  routes:
  - match:
      severity: critical
    receiver: 'web.hook'
    group_wait: 5s
    repeat_interval: 30m
  - match:
      alertname: HighMagnitudeEarthquake
    receiver: 'web.hook'
    group_wait: 0s
    repeat_interval: 15m
  - match:
      alertname: EarthquakeSwarm
    receiver: 'web.hook'
    group_wait: 30s
    repeat_interval: 2h

receivers:
- name: 'web.hook'
  webhook_configs:
  - url: 'http://seismic-webhook-receiver:5001/webhook'
    send_resolved: true

inhibit_rules:
- source_match:
    severity: 'critical'
  target_match:
    severity: 'warning'
  equal: ['alertname', 'region']