kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: seismic-insights
nodes:
  - role: control-plane
    extraPortMappings:
    - containerPort: 30086
      hostPort: 8086
      listenAddress: "0.0.0.0"
      protocol: TCP
    - containerPort: 30081
      hostPort: 8081
      listenAddress: "0.0.0.0"
      protocol: TCP
    - containerPort: 30040
      hostPort: 4040
      listenAddress: "0.0.0.0"
      protocol: TCP
    - containerPort: 30000
      hostPort: 3001
      listenAddress: "0.0.0.0"
      protocol: TCP
    - containerPort: 30090
      hostPort: 9090
      listenAddress: "0.0.0.0"
      protocol: TCP
    - containerPort: 30093
      hostPort: 9093
      listenAddress: "0.0.0.0"
      protocol: TCP
    - containerPort: 30001
      hostPort: 5001
      listenAddress: "0.0.0.0"
      protocol: TCP
  - role: worker
  - role: worker
