apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: seismic-insights
  labels:
    app: prometheus
spec:
  selector:
    app: prometheus
  ports:
  - name: http
    port: 9090
    targetPort: 9090
    nodePort: 30090
    protocol: TCP
  type: NodePort
