apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: seismic-insights
  labels:
    app: alertmanager
spec:
  selector:
    app: alertmanager
  ports:
  - name: http
    port: 9093
    targetPort: 9093
    nodePort: 30093
    protocol: TCP
  type: NodePort
