global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "seismic_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'influxdb'
    static_configs:
      - targets: ['seismic-influxdb:8086']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'grafana'
    static_configs:
      - targets: ['seismic-grafana:3000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9092']
    scrape_interval: 30s

  - job_name: 'seismic-metrics'
    static_configs:
      - targets: ['seismic-metrics-exporter:9101']
    scrape_interval: 15s
    metrics_path: '/metrics'