apiVersion: 1

datasources:
  - name: InfluxDB-SeismicData
    type: influxdb
    access: proxy
    url: http://seismic-influxdb:8086
    secureJsonData:
      token: ${INFLUXDB_TOKEN}
    jsonData:
      version: Flux
      organization: ${INFLUXDB_ORG}
      defaultBucket: ${INFLUXDB_BUCKET}
      tlsSkipVerify: true
    isDefault: true
    editable: true