apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: seismic-insights
spec:
  selector:
    app: kafka
  ports:
  - name: kafka
    port: 9092
    targetPort: 9092
    protocol: TCP
  - name: controller
    port: 9093
    targetPort: 9093
    protocol: TCP
  type: ClusterIP
