apiVersion: v1
kind: Service
metadata:
  name: webhook-receiver
  namespace: seismic-insights
  labels:
    app: webhook-receiver
spec:
  selector:
    app: webhook-receiver
  ports:
  - name: http
    port: 5001
    targetPort: 5001
    nodePort: 30001
    protocol: TCP
  type: NodePort
