version: '3.8'

services:
  influxdb:
    image: influxdb:2.7
    container_name: seismic-influxdb
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin123456
      - DOCKER_INFLUXDB_INIT_ORG=seismic-insights
      - DOCKER_INFLUXDB_INIT_BUCKET=earthquakes
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=seismic-insights-token
    volumes:
      - influxdb_data:/var/lib/influxdb2
      - influxdb_config:/etc/influxdb2

volumes:
  influxdb_data:
  influxdb_config:
