apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-provisioning
  namespace: seismic-insights
data:
  datasources.yml: |
    apiVersion: 1

    datasources:
      - name: InfluxDB-SeismicData
        type: influxdb
        access: proxy
        url: http://influxdb:8086
        secureJsonData:
          token: ${INFLUXDB_TOKEN}
        jsonData:
          version: Flux
          organization: ${INFLUXDB_ORG}
          defaultBucket: ${INFLUXDB_BUCKET}
          tlsSkipVerify: true
        isDefault: true
        editable: true
  dashboards.yml: |
    apiVersion: 1

    providers:
      - name: 'SeismicInsights'
        orgId: 1
        folder: 'Seismic Monitoring'
        type: file
        disableDeletion: false
        updateIntervalSeconds: 10
        allowUiUpdates: true
        options:
          path: /var/lib/grafana/dashboards
