apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: seismic-insights
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: seismic-grafana
        image: grafana/grafana-oss:latest
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: seismic-config
        env:
        - name: GF_SECURITY_ADMIN_USER
          valueFrom:
            secretKeyRef:
              name: seismic-secrets
              key: GRAFANA_ADMIN_USER
        - name: GF_SECURITY_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: seismic-secrets
              key: GRAFANA_ADMIN_PASSWORD
        - name: GF_INSTALL_PLUGINS
          value: "grafana-worldmap-panel,grafana-clock-panel,yesoreyeram-boomtheme-panel"
        - name: GF_PATHS_PROVISIONING
          value: "/etc/grafana/provisioning"
        - name: GF_LOG_LEVEL
          value: "debug"
        - name: INFLUXDB_USERNAME
          valueFrom:
            secretKeyRef:
              name: seismic-secrets
              key: INFLUXDB_USERNAME
        - name: INFLUXDB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: seismic-secrets
              key: INFLUXDB_PASSWORD
        - name: INFLUXDB_TOKEN
          valueFrom:
            secretKeyRef:
              name: seismic-secrets
              key: INFLUXDB_TOKEN
        - name: INFLUXDB_ORG
          valueFrom:
            configMapKeyRef:
              name: seismic-config
              key: INFLUXDB_ORG
        - name: INFLUXDB_BUCKET
          valueFrom:
            configMapKeyRef:
              name: seismic-config
              key: INFLUXDB_BUCKET
        volumeMounts:
        - name: grafana-data
          mountPath: /var/lib/grafana
        - name: grafana-datasources
          mountPath: /etc/grafana/provisioning/datasources
        - name: grafana-dashboard-provider
          mountPath: /etc/grafana/provisioning/dashboards
        - name: grafana-dashboards
          mountPath: /var/lib/grafana/dashboards
      volumes:
      - name: grafana-data
        emptyDir: {}
      - name: grafana-datasources
        configMap:
          name: grafana-datasources
      - name: grafana-dashboard-provider
        configMap:
          name: grafana-dashboard-provider
      - name: grafana-dashboards
        configMap:
          name: grafana-dashboards
      restartPolicy: Always
