apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: seismic-insights
  labels:
    app: grafana
spec:
  selector:
    app: grafana
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    nodePort: 30000
    protocol: TCP
  type: NodePort
