apiVersion: v1
kind: Service
metadata:
  name: metrics-exporter
  namespace: seismic-insights
  labels:
    app: metrics-exporter
spec:
  selector:
    app: metrics-exporter
  ports:
  - name: http
    port: 9101
    targetPort: 9101
    protocol: TCP
  type: ClusterIP
